### ISSUE TITLE
A bit confused on what this can do?

### ISSUE THREAD

**Issue by MostHated** [rainersigwald/bumblebee#5]
Hey there,
    When I think of go fmt, I think of formatting the code, such as tabs, returns/blank lines, etc. Is that not what this is used for?

Thanks,
-MH

**Comment by rainersigwald** [comment]
Right now this repo doesn't do much. But no, this is intended to perform a subset of `go fmt` operations, specifically `go fmt -r` rewrite rules.

[`dotnet format`](https://github.com/dotnet/format) can do formatting for .NET code, though, if that's what you're looking for.

**Comment by MostHated** [comment]
I appreciate the reply, and that is understood. I actually came across that one not too long after I found this one. It seems to do the job decently. 

Thanks,
-MH
